SKILLS_DB = [
    "python",
    "java",
    "c++",
    "javascript",
    "html",
    "css",
    "react",
    "node.js",
    "express.js",
    "mongodb",
    "mysql",
    "sql",
    "git",
    "github",
    "rest api",
    "docker",
    "aws",
    "firebase",
    "machine learning",
    "deep learning",
    "tensorflow",
    "pytorch",
    "flask",
    "django"
]